// Generated by CoffeeScript 1.3.3
(function() {
  var exec, execute, log,
    __slice = [].slice;

  exec = require('child_process').exec;

  log = console.log;

  method;


  parameters;


  header;


  execute = function(cmd, cb) {
    log("this is your command: " + cmd);
    return exec("" + cmd, function(err, stdout, stderr) {
      if (!(err != null)) {
        return log("successful execution of command: " + cmd);
      } else {
        return log("there was an error: " + err);
      }
    });
  };

  module.exports = {
    play: function() {
      return execute('play');
    },
    startsession: function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return log("these are args: " + args);
    },
    help: function() {
      return log("help");
    }
  };

}).call(this);
