// Generated by CoffeeScript 1.3.3
(function() {
  var api, exec, execute, log;

  exec = require('child_process').exec;

  api = require('./api.coffee');

  log = console.log;

  execute = function(cmd, cb) {
    var calback;
    log("this is your command: " + cmd);
    calback = function(error, response) {
      if (cb != null) {
        return cb(error, response);
      }
    };
    return exec("" + cmd, function(err, stdout, stderr) {
      if (err != null) {
        return log("successful execution of command: " + cmd);
      } else {
        return log("there was an error: " + err);
      }
    });
  };

  module.exports = {
    play: function() {
      return execute('play');
    },
    auth: function() {
      return api.authenticateUser();
    },
    session: function() {
      return api.startSession();
    },
    help: function() {
      log("\nUsage:\n");
      return log("    groove <command> <args>");
    }
  };

}).call(this);
